const Z={...JSON.parse(window.__NICE_DATA),ai:JSON.parse(window.__NICE_AI)},D=Z.d,AI=Z.ai,F=new Intl.NumberFormat("pt-BR"),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const P=Z.p.map(x=>({id:x[0],year:x[1],type:D.type[x[2]],course:D.course[x[3]],mod:D.modality[x[4]],unit:D.unit[x[5]],reach:D.reach[x[6]],theme:D.themeTransversal[x[7]],inf:x[8],part:x[9],stud:x[10],est:!!(x[11]&1),ext:!!(x[11]&2),partner:!!(x[11]&4),cert:!!(x[11]&8),lab:!!(x[11]&16),veh:!!(x[11]&32),people:x[12]})),R=Z.r.map(x=>({id:x[0],year:x[1],type:D.type[x[2]],course:D.course[x[3]]}));
const uniq=a=>[...new Set(a.filter(x=>x!==null&&x!==undefined&&x!==""))].sort((a,b)=>String(a).localeCompare(String(b),"pt-BR")),sum=(a,k)=>a.reduce((s,x)=>s+(+x[k]||0),0),gc=(a,k)=>{const m={};a.forEach(x=>{let z=x[k]||"Não informado";m[z]=(m[z]||0)+1});return m},gs=(a,k,v)=>{const m={};a.forEach(x=>{let z=x[k]||"Não informado";m[z]=(m[z]||0)+(+x[v]||0)});return m},top=(m,n=10)=>Object.entries(m).sort((a,b)=>b[1]-a[1]).slice(0,n);
function sel(id,vals,all=true){let s=q("#"+id);s.innerHTML="";if(all){let o=document.createElement("option");o.value="";o.textContent="Todos";s.append(o)}vals.forEach(v=>{let o=document.createElement("option");o.value=v;o.textContent=v;s.append(o)});return s}
sel("fy",uniq(P.map(x=>x.year)).map(String));sel("fc",uniq(P.map(x=>x.course)));sel("ft",uniq(P.map(x=>x.type)));sel("fm",uniq(P.map(x=>x.mod)));sel("fu",uniq(P.map(x=>x.unit)));sel("fr",uniq(P.map(x=>x.reach)));
function cur(){return{y:q("#fy").value,c:q("#fc").value,t:q("#ft").value,m:q("#fm").value,u:q("#fu").value,r:q("#fr").value}}
function pm(x,f){return(!f.y||String(x.year)===f.y)&&(!f.c||x.course===f.c)&&(!f.t||x.type===f.t)&&(!f.m||x.mod===f.m)&&(!f.u||x.unit===f.u)&&(!f.r||x.reach===f.r)}function rm(x,f){return(!f.y||String(x.year)===f.y)&&(!f.c||x.course===f.c)&&(!f.t||x.type===f.t)}
function canv(id){let c=q("#"+id),d=devicePixelRatio||1,r=c.getBoundingClientRect(),w=Math.max(300,r.width),h=300;c.width=w*d;c.height=h*d;c.style.height=h+"px";let x=c.getContext("2d");x.scale(d,d);x.clearRect(0,0,w,h);x.font="11px Segoe UI";return{x,w,h}}
function bar(id,e){let{x,w,h}=canv(id);if(!e.length){x.fillText("Sem dados.",15,25);return}let mx=Math.max(...e.map(a=>a[1]),1),pl=160,pr=42,pt=15,pb=20,g=5,bh=Math.max(11,(h-pt-pb-g*(e.length-1))/e.length);e.forEach((a,i)=>{let y=pt+i*(bh+g),bw=(w-pl-pr)*a[1]/mx;x.fillStyle=i===0?"#e97824":"#2f75b5";x.fillRect(pl,y,bw,bh);x.fillStyle="#334155";x.textAlign="right";x.textBaseline="middle";let l=String(a[0]);if(l.length>25)l=l.slice(0,23)+"…";x.fillText(l,pl-7,y+bh/2);x.textAlign="left";x.fillStyle="#64748b";x.fillText(F.format(Math.round(a[1])),Math.min(w-40,pl+bw+5),y+bh/2)})}
function donut(id,e){let{x,w,h}=canv(id);if(!e.length)return;let tot=e.reduce((s,a)=>s+a[1],0)||1,cx=w*.31,cy=h*.5,r=Math.min(w,h)*.26,inn=r*.58,C=["#2f75b5","#e97824","#278257","#7c6db3","#8896a6"],a=-Math.PI/2;e.forEach((z,i)=>{let da=2*Math.PI*z[1]/tot;x.beginPath();x.moveTo(cx,cy);x.arc(cx,cy,r,a,a+da);x.closePath();x.fillStyle=C[i%C.length];x.fill();a+=da});x.beginPath();x.arc(cx,cy,inn,0,2*Math.PI);x.fillStyle="#fff";x.fill();x.fillStyle="#17365d";x.textAlign="center";x.font="700 17px Segoe UI";x.fillText(F.format(tot),cx,cy+5);x.font="11px Segoe UI";x.textAlign="left";e.forEach((z,i)=>{let xx=w*.59,yy=43+i*29;x.fillStyle=C[i%C.length];x.fillRect(xx,yy-8,9,9);x.fillStyle="#475569";let l=String(z[0]);if(l.length>24)l=l.slice(0,22)+"…";x.fillText(l,xx+14,yy);x.fillStyle="#64748b";x.fillText((100*z[1]/tot).toFixed(1)+"%",xx+14,yy+12)})}
function annual(p){let{x,w,h}=canv("annual"),ys=uniq(P.map(z=>z.year)).sort(),f=cur(),a=ys.map(y=>[y,p.filter(z=>z.year===y).length,R.filter(z=>z.year===y&&(!f.c||z.course===f.c)&&(!f.t||z.type===f.t)).length]),mx=Math.max(...a.flatMap(z=>[z[1],z[2]]),1),pl=38,pr=10,pt=25,pb=37,pw=w-pl-pr,ph=h-pt-pb,gw=pw/a.length,bw=Math.min(30,gw*.28);a.forEach((z,i)=>{let cx=pl+gw*(i+.5);[[z[1],"#2f75b5",-bw*.55],[z[2],"#e97824",bw*.55]].forEach(v=>{let hh=ph*v[0]/mx;x.fillStyle=v[1];x.fillRect(cx+v[2]-bw/2,pt+ph-hh,bw,hh)});x.fillStyle="#475569";x.textAlign="center";x.fillText(z[0],cx,h-15)});x.fillStyle="#2f75b5";x.fillRect(pl,4,11,7);x.fillStyle="#475569";x.textAlign="left";x.fillText("Protocolos",pl+16,11);x.fillStyle="#e97824";x.fillRect(pl+85,4,11,7);x.fillStyle="#475569";x.fillText("Relatórios",pl+101,11)}
function update(){let f=cur(),p=P.filter(x=>pm(x,f)),r=R.filter(x=>rm(x,f));q("#kp").textContent=F.format(p.length);q("#kr").textContent=F.format(r.length);q("#ki").textContent=F.format(sum(p,"inf"));q("#kc").textContent=F.format(sum(p,"part"));q("#ks").textContent=F.format(sum(p,"stud"));let ppl=new Set;p.forEach(x=>x.people.forEach(y=>ppl.add(y)));q("#kd").textContent=F.format(ppl.size);q("#ke").textContent=F.format(p.filter(x=>x.ext).length);q("#kx").textContent=F.format(p.filter(x=>["Externo/comunidade","Misto (interno + externo)"].includes(x.reach)).length);q("#mp").textContent="Parceiros: "+F.format(p.filter(x=>x.partner).length);q("#mcert").textContent="Certificados: "+F.format(p.filter(x=>x.cert).length);q("#mlab").textContent="Lab./auditório: "+F.format(p.filter(x=>x.lab).length);q("#mveh").textContent="Veículo: "+F.format(p.filter(x=>x.veh).length);q("#mest").textContent="Participação estimada: "+F.format(p.filter(x=>x.est).length);annual(p);bar("courses",top(gc(p,"course")));bar("types",top(gc(p,"type")));donut("reach",top(gc(p,"reach"),5));donut("mods",top(gc(p,"mod"),5));bar("parts",top(gs(p,"course","part")));let tm={};p.forEach(x=>{if(x.theme==="Não informado")return;x.theme.split(/[,;]/).forEach(t=>{t=t.trim();if(t)tm[t]=(tm[t]||0)+1})});bar("themes",top(tm));bar("units",top(gc(p,"unit")));let pc={};p.forEach(x=>{let c=x.course,z=pc[c]||(pc[c]={e:0,p:0,s:0,ex:0,x:0});z.e++;z.p+=x.part;z.s+=x.stud;if(x.ext)z.ex++;if(["Externo/comunidade","Misto (interno + externo)"].includes(x.reach))z.x++});let rc=gc(r,"course");q("#tb").innerHTML=Object.entries(pc).sort((a,b)=>b[1].e-a[1].e).slice(0,35).map(([c,z])=>`<tr><td>${esc(c)}</td><td>${z.e}</td><td>${rc[c]||0}</td><td>${F.format(z.p)}</td><td>${F.format(z.s)}</td><td>${z.ex}</td><td>${z.x}</td></tr>`).join("")}
["fy","fc","ft","fm","fu","fr"].forEach(i=>q("#"+i).onchange=update);q("#reset").onclick=()=>{["fy","fc","ft","fm","fu","fr"].forEach(i=>q("#"+i).value="");update()};q("#csv").onclick=()=>{let p=P.filter(x=>pm(x,cur())),cols=["id","year","course","type","mod","unit","reach","inf","part","stud","est","ext"],E=v=>'"'+String(v??"").replaceAll('"','""')+'"',s=[cols.join(";"),...p.map(x=>cols.map(k=>E(x[k])).join(";"))].join("\n"),b=new Blob(["\ufeff"+s],{type:"text/csv;charset=utf-8"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="nice_eventos_filtrado.csv";a.click()};
function pct(x){return(100*x).toFixed(1)+"%"}q("#ain").textContent=F.format(AI.n);q("#rfauc").textContent=AI.metrics.rf.auc.toFixed(3);q("#mlpauc").textContent=AI.metrics.mlp.auc.toFixed(3);q("#thr").textContent="≥ "+AI.thr;
q("#models").innerHTML=[["Machine Learning · Random Forest",AI.metrics.rf],["Deep Learning · MLP 64-32-16",AI.metrics.mlp]].map(([n,m])=>`<div class="model"><h3>${n}</h3><div class="mr"><span>Acurácia</span><b>${pct(m.acc)}</b></div><div class="mr"><span>Acurácia balanceada</span><b>${pct(m.bal)}</b></div><div class="mr"><span>F1</span><b>${m.f1.toFixed(3)}</b></div><div class="mr"><span>AUC-ROC</span><b>${m.auc.toFixed(3)}</b></div></div>`).join("");q("#quality").innerHTML=AI.quality.map(z=>`<div class="qrow"><span>${esc(z[0])}</span><div class="bar"><i style="width:${z[1]}%"></i></div><b>${z[1].toFixed(1)}%</b></div>`).join("");
bar("importance",AI.imp.map(z=>[z[0],z[1]*1000]));let groups={};AI.clusters.rows.forEach(z=>(groups[z[1]]??=[]).push(z));q("#clusterCards").innerHTML=Object.entries(groups).map(([k,a])=>`<div class="cluster"><h3>Perfil ${+k+1} · ${esc(a[0][2])}</h3><p>${a.map(z=>esc(z[0])).join(", ")}</p><b>${a.length} curso(s) · silhouette ${AI.clusters.sil}</b></div>`).join("");q("#ctb").innerHTML=AI.clusters.rows.map(z=>`<tr><td>${esc(z[0])}</td><td>Perfil ${z[1]+1} · ${esc(z[2])}</td><td>${z[3]}</td><td>${z[4]}</td><td>${z[5]}%</td><td>${z[6]}%</td><td>${z[7]}%</td></tr>`).join("");q("#atb").innerHTML=AI.anom.map(z=>`<tr><td>${z[0]}</td><td>${z[1]}</td><td>${esc(z[2])}</td><td>${esc(z[3])}</td><td>${z[4]}</td><td>${esc(z[5])}</td><td>${z[6]}</td></tr>`).join("");
const C=AI.pre.cats;sel("sy",["2021","2022","2023","2024","2025","2026","2027"],false);q("#sy").value="2026";sel("sc",C.course,false);sel("st",C.type,false);sel("sm",C.modality,false);sel("sr",C.reach,false);sel("sth",C.themeTransversal,false);
function vec(){let pr=AI.pre,v=[(Number(q("#sy").value)-pr.ym)/pr.ys],o={type:q("#st").value,course:q("#sc").value,modality:q("#sm").value,reach:q("#sr").value,themeTransversal:q("#sth").value,extension:q("#se").checked,partner:q("#sp").checked,certificate:q("#sce").checked,lab:q("#sl").checked,vehicle:q("#sv").checked};pr.cf.forEach(f=>pr.cats[f].forEach(c=>v.push(o[f]===c?1:0)));pr.bf.forEach(f=>v.push(o[f]?1:0));return v}
function rfp(v){let s=0;AI.rf.forEach(t=>{let n=0;while(t[0][n]>=0)n=v[t[0][n]]<=t[1][n]?t[2][n]:t[3][n];s+=t[4][n]});return s/AI.rf.length}function sig(x){return 1/(1+Math.exp(-Math.max(-35,Math.min(35,x))))}function mlpp(v){let a=v,W=AI.mlp[0],B=AI.mlp[1];W.forEach((m,l)=>{let o=new Array(B[l].length).fill(0);for(let j=0;j<o.length;j++){let z=B[l][j];for(let i=0;i<a.length;i++)z+=a[i]*m[i][j];o[j]=l===W.length-1?sig(z):Math.max(0,z)}a=o});return a[0]}function lab(p){return p>=.7?"Tendência alta":p>=.5?"Tendência moderadamente alta":p>=.3?"Tendência moderadamente baixa":"Tendência baixa"}function infer(){let v=vec(),a=Math.max(0,Math.min(1,rfp(v))),b=Math.max(0,Math.min(1,mlpp(v)));q("#prf").textContent=pct(a);q("#pmlp").textContent=pct(b);q("#mrf").style.width=100*a+"%";q("#mmlp").style.width=100*b+"%";q("#lrf").textContent=lab(a);q("#lmlp").textContent=lab(b)}q("#run").onclick=infer;infer();
qa(".tabs button").forEach(b=>b.onclick=()=>{qa(".tabs button").forEach(x=>x.classList.toggle("on",x===b));qa(".tab").forEach(x=>x.classList.toggle("on",x.id===b.dataset.tab));setTimeout(()=>{if(b.dataset.tab==="visao")update();if(b.dataset.tab==="ia")bar("importance",AI.imp.map(z=>[z[0],z[1]*1000]))},0)});window.onresize=()=>{clearTimeout(window.rt);window.rt=setTimeout(()=>{if(q("#visao").classList.contains("on"))update();if(q("#ia").classList.contains("on"))bar("importance",AI.imp.map(z=>[z[0],z[1]*1000]))},170)};update();
