(()=>{
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)], F=new Intl.NumberFormat("pt-BR");
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const norm=s=>String(s??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ");
const synonymGroups=[
 ["saude mental","ansiedade","depressao","emocional","suicidio","estresse","psicologia"],
 ["adolescente","adolescentes","jovem","jovens","infancia","crianca","criancas"],
 ["meio ambiente","ambiental","sustentabilidade","reciclagem","residuo","clima","ecologia"],
 ["tecnologia","inovacao","digital","software","inteligencia artificial","computacao"],
 ["educacao","ensino","aprendizagem","escola","formacao","capacitacao","pedagogia"],
 ["direitos humanos","cidadania","justica","violencia","desigualdade","inclusao"],
 ["alimentacao","nutricao","alimento","dieta","obesidade"],
 ["idoso","idosos","envelhecimento","terceira idade"],
 ["genero","mulher","mulheres","feminino","saude da mulher"],
 ["empreendedorismo","trabalho","emprego","negocio","gestao","carreira"]
].map(g=>g.map(norm));
function expandQuery(s){const base=norm(s);if(!base)return[];const toks=new Set(base.split(" ").filter(x=>x.length>2));synonymGroups.forEach(g=>{if(g.some(x=>base.includes(x)||toks.has(x)))g.forEach(x=>x.split(" ").forEach(t=>toks.add(t)))});return[...toks]}
function setupCanvas(id){const c=q("#"+id);if(!c)return null;const d=window.devicePixelRatio||1,r=c.getBoundingClientRect(),w=Math.max(320,r.width),h=300;c.width=w*d;c.height=h*d;c.style.height=h+"px";const x=c.getContext("2d");x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);x.font="11px Segoe UI";return{x,w,h}}
function hbar(id,rows,format=v=>F.format(Math.round(v))){const z=setupCanvas(id);if(!z)return;const{x,w,h}=z;if(!rows.length){x.fillStyle="#64748b";x.fillText("Sem dados.",15,25);return}const max=Math.max(...rows.map(r=>Math.abs(r[1])),1),left=185,right=55,top=14,bottom=18,gap=5,bh=Math.max(11,(h-top-bottom-gap*(rows.length-1))/rows.length);rows.forEach((r,i)=>{const y=top+i*(bh+gap),bw=(w-left-right)*Math.abs(r[1])/max;x.fillStyle=r[1]<0?"#b85c5c":(i===0?"#e97824":"#2f75b5");x.fillRect(left,y,bw,bh);x.fillStyle="#334155";x.textAlign="right";x.textBaseline="middle";let lab=String(r[0]);if(lab.length>29)lab=lab.slice(0,27)+"…";x.fillText(lab,left-7,y+bh/2);x.textAlign="left";x.fillStyle="#64748b";x.fillText(format(r[1]),Math.min(w-52,left+bw+5),y+bh/2)})}
function donut(id,rows){const z=setupCanvas(id);if(!z)return;const{x,w,h}=z,total=rows.reduce((a,b)=>a+b[1],0)||1,cx=w*.31,cy=h*.5,r=Math.min(w,h)*.27,inn=r*.58,C=["#278257","#e97824","#2f75b5","#7c6db3"];let a=-Math.PI/2;rows.forEach((v,i)=>{const da=2*Math.PI*v[1]/total;x.beginPath();x.moveTo(cx,cy);x.arc(cx,cy,r,a,a+da);x.closePath();x.fillStyle=C[i%C.length];x.fill();a+=da});x.beginPath();x.arc(cx,cy,inn,0,2*Math.PI);x.fillStyle="#fff";x.fill();x.textAlign="center";x.fillStyle="#17365d";x.font="700 18px Segoe UI";x.fillText(F.format(total),cx,cy+5);x.font="11px Segoe UI";x.textAlign="left";rows.forEach((v,i)=>{let xx=w*.60,yy=65+i*38;x.fillStyle=C[i%C.length];x.fillRect(xx,yy-8,10,10);x.fillStyle="#475569";x.fillText(v[0],xx+16,yy);x.fillStyle="#64748b";x.fillText((100*v[1]/total).toFixed(1)+"%",xx+16,yy+13)})}
function fillSelect(id,vals,label="Todos"){const s=q("#"+id);if(!s)return;s.innerHTML=`<option value="">${label}</option>`+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("")}
function qualityColor(v){return v>=80?"good":v>=60?"mid":"bad"}

fetch("docintel_payload_v2.json?ts="+Date.now(),{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Falha HTTP "+r.status+" ao buscar a base documental");return r.json()}).then(C=>{
 const D=C.dict;
 const docs=C.d.map((r,i)=>({id:i+1,y:r[0]||null,c:D.c[r[1]],t:D.t[r[2]],q:r[3],qb:r[3]>=80?"Alta":r[3]>=60?"Moderada":"Baixa",tp:r[4].map(x=>D.tp[x]),ods:r[5].map(x=>D.ods[x]),kw:r[6].map(x=>D.kw[x]),sim:r[7],m:r[8]||null,dup:!!r[9],fl:r[10].map(x=>D.fl[x])}));
 const DB={...C,docs};window.__NICE_DOCINTEL=DB;
 q("#dkDocs").textContent=F.format(C.n);q("#dkHigh").textContent=F.format(C.s.quality.Alta||0);q("#dkDup").textContent=F.format(C.s.duplicatePairs||0);q("#dkMatch").textContent=F.format(C.s.highConfidenceMatches||0);
 fillSelect("dy",[...new Set(docs.map(d=>d.y))].filter(Boolean).sort().map(String));fillSelect("dc",D.c);fillSelect("dtp",D.tp);fillSelect("dods",D.ods);fillSelect("dqual",["Alta","Moderada","Baixa"]);
 const drawSummary=()=>{hbar("dTopics",C.s.topics.slice(0,10));hbar("dOds",C.s.ods.slice(0,10));donut("dQuality",[["Alta",C.s.quality.Alta||0],["Moderada",C.s.quality.Moderada||0],["Baixa",C.s.quality.Baixa||0]]);hbar("dTrends",C.s.topicTrends.slice().sort((a,b)=>Math.abs(b[5])-Math.abs(a[5])).slice(0,10).map(x=>[x[0],x[5]]),v=>(v>0?"+":"")+v.toFixed(1)+" p.p.")};
 drawSummary();
 const byId=id=>docs[id-1];
 function filtered(){const y=q("#dy").value,c=q("#dc").value,tp=q("#dtp").value,ods=q("#dods").value,qual=q("#dqual").value,terms=expandQuery(q("#dsearch").value);return docs.map(d=>{if(y&&String(d.y)!==y)return null;if(c&&d.c!==c)return null;if(tp&&!d.tp.includes(tp))return null;if(ods&&!d.ods.includes(ods))return null;if(qual&&d.qb!==qual)return null;const hay=norm([d.c,d.t,...d.tp,...d.ods,...d.kw].join(" "));let score=0;terms.forEach(t=>{if(d.tp.some(x=>norm(x).includes(t)))score+=5;if(d.kw.some(x=>norm(x).includes(t)))score+=4;if(norm(d.c).includes(t))score+=3;if(d.ods.some(x=>norm(x).includes(t)))score+=3;if(norm(d.t).includes(t))score+=2;if(hay.includes(t))score+=1});if(terms.length&&score===0)return null;return{d,score}}).filter(Boolean).sort((a,b)=>b.score-a.score||b.d.q-a.d.q||(b.d.y||0)-(a.d.y||0))}
 function showDoc(id){const d=byId(id);if(!d)return;const sims=d.sim.map(x=>{const z=byId(x[0]);return`<li><button class="linkbtn" data-sim="${z.id}">Ação #${z.id}</button> · ${esc(z.c)} · ${z.y||"–"} · ${(x[1]*100).toFixed(1)}%</li>`}).join("")||"<li>Nenhuma similaridade relevante acima do limiar.</li>";const m=d.m?`Relatório #${d.m[0]} · confiança ${(d.m[1]*100).toFixed(1)}%`:"Nenhuma correspondência forte identificada automaticamente.";q("#docDetail").innerHTML=`<h2>Ficha de inteligência · Ação #${d.id}</h2><div class="doc-meta"><span>${d.y||"–"}</span><span>${esc(d.c)}</span><span>${esc(d.t)}</span></div><div class="doc-score"><div><small>Completude documental</small><strong>${d.q}/100</strong></div><div class="scorebar"><i style="width:${d.q}%"></i></div></div><h3>Temas identificados</h3><div class="taglist">${d.tp.map(x=>`<span>${esc(x)}</span>`).join("")}</div><h3>ODS potenciais</h3><div class="taglist ods">${d.ods.map(x=>`<span>${esc(x)}</span>`).join("")}</div><h3>Palavras-chave derivadas</h3><div class="taglist kw">${d.kw.map(x=>`<span>${esc(x)}</span>`).join("")}</div><h3>Lacunas documentais</h3>${d.fl.length?`<ul class="flaglist">${d.fl.map(x=>`<li>${esc(x)}</li>`).join("")}</ul>`:"<p class='oktext'>Nenhuma lacuna principal detectada pelas regras de completude.</p>"}<h3>Projetos semelhantes</h3><ul class="similar-list">${sims}</ul><h3>Correspondência provável com relatório</h3><p>${m}</p><p class="doc-disclaimer">A ficha é gerencial e automatizada. Temas, ODS, similaridade e correspondências devem ser validados quando usados em relatórios oficiais.</p>`;qa("[data-sim]").forEach(b=>b.onclick=()=>showDoc(Number(b.dataset.sim)))}
 function render(){const arr=filtered();q("#dcount").textContent=F.format(arr.length)+" ação(ões) encontrada(s)";q("#docResults").innerHTML=arr.slice(0,60).map(({d})=>`<tr data-id="${d.id}" class="doc-row"><td>Ação #${d.id}${d.dup?' <span class="mini-alert">similar</span>':''}</td><td>${d.y||"–"}</td><td>${esc(d.c)}</td><td>${esc(d.t)}</td><td>${esc(d.tp.join(", "))}</td><td>${esc(d.ods.join(", "))}</td><td><span class="qbadge ${qualityColor(d.q)}">${d.q}/100</span></td></tr>`).join("");qa("#docResults tr").forEach(r=>r.onclick=()=>showDoc(Number(r.dataset.id)));if(arr.length)showDoc(arr[0].d.id)}
 q("#dgo").onclick=render;q("#dsearch").addEventListener("keydown",e=>{if(e.key==="Enter")render()});["dy","dc","dtp","dods","dqual"].forEach(id=>q("#"+id).onchange=render);q("#dclear").onclick=()=>{q("#dsearch").value="";["dy","dc","dtp","dods","dqual"].forEach(id=>q("#"+id).value="");render()};
 q("#dupTable").innerHTML=C.dup.slice(0,50).map(x=>`<tr><td>Ação #${x[0]}</td><td>Ação #${x[1]}</td><td>${(x[2]*100).toFixed(1)}%</td><td>${(x[3]*100).toFixed(1)}%</td></tr>`).join("");
 q("#matchTable").innerHTML=C.m.slice(0,80).map(x=>`<tr><td>Protocolo #${x[0]}</td><td>Relatório #${x[1]}</td><td>${esc(x[3])}</td><td>${x[4]||"–"}</td><td>${x[5]||"–"}</td><td>${(x[2]*100).toFixed(1)}%</td></tr>`).join("");
 render();
 const docTab=qa(".tabs button").find(b=>b.dataset.tab==="doc");if(docTab)docTab.addEventListener("click",()=>setTimeout(drawSummary,40));
 window.addEventListener("resize",()=>{if(q("#doc")?.classList.contains("on")){clearTimeout(window.__docResize);window.__docResize=setTimeout(drawSummary,150)}});
 console.info("NICE Inteligência Documental v1 OK",C.n);
}).catch(err=>{console.error(err);const tab=q("#doc");if(tab)tab.insertAdjacentHTML("afterbegin",`<div class="doc-error">Falha ao carregar a Inteligência Documental: ${esc(err.message||err)}</div>`)});
})();